baseURL = 'https://santacloud.dev/'
languageCode = 'en-us'
title = 'Santacloud'
theme = 'hugo-blog-awesome'
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[[params.socialIcons]]
name = "github"
url = "https://github.com/thesantacloud"

[[params.socialIcons]]
name = "x"
url = "https://x.com/thesantacloud"

[[params.socialIcons]]
name = "email"
url = "dor@santacloud.dev"

[menu]
[[menu.main]]
pageRef = "/"
name = 'Home'
url = '/'
weight = 10
[[menu.main]]
pageRef = "posts"
name = 'Posts'
url = '/posts/'
weight = 20

[params]
sitename = "Santacloud"
defaultColor = "dark"
description = "A blog about tech stuff"
mainSections = ['posts']
toc = false                             # set to false to disable table of contents 'globally'
tocOpen = false                         # set to true to open table of contents by default
goToTop = true                          # set to false to disable 'go to top' button
rssFeedDescription = "summary"

[params.author]
intro = "Santacloud"
name = "Dor Munis"
avatar = "santacloud-logo-black.svg"
description = "I tinker with software and hardware and make machines do what I want"

[params.webmanifest]
name = "Santacloud"
short_name = "Santacloud"
start_url = "https://santacloud.dev/"
theme_color = "#434648"               # default is "#434648" (base color of text). Also will override html `<meta name="theme-color" />`
background_color = "#fff"             # by default depend on "params.defaultColor" for "light" or "auto" will be set to "#fff" for dark will be "#131418" (color of dark mode background)
display = "standalone"

[services]
[services.googleAnalytics]
ID = "$HUGO_GOOGLE_ANALYTICS_ID"
