baseURL = 'https://santacloud.dev/'
languageCode = 'en-us'
title = 'Santacloud'
theme = 'hugo-blog-awesome'

enableEmoji = true
ignoreErrors = ["additional-script-loading-error"]

[markup]
[markup.highlight]
noClasses = false
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 4
ordered = false

[[params.socialIcons]]
name = "github"
url = "https://github.com/thesantacloud"

[[params.socialIcons]]
name = "x"
url = "https://x.com/thesantacloud"

[[params.socialIcons]]
name = "email"
url = "dor@santacloud.dev"

[menu]
[[menu.main]]
pageRef = "/"
name = 'Home'
url = '/'
weight = 10
[[menu.main]]
pageRef = "posts"
name = 'Posts'
url = '/posts/'
weight = 20

[params]
sitename = "Santacloud"
defaultColor = "dark"
description = "A blog about tech stuff"
mainSections = ['posts']
toc = false                             # set to false to disable table of contents 'globally'
tocOpen = false                         # set to true to open table of contents by default
goToTop = true                          # set to false to disable 'go to top' button
rssFeedDescription = "summary"

[params.author]
intro = "Santacloud"
name = "Dor Munis"
description = "I tinker with software and hardware and make machines do what I want"

[module]
[[module.mounts]]
source = '/Users/dormunis/Documents/obsidian-vault/blog/'
target = 'content/posts'

[services]
[services.googleAnalytics]
ID = "G-31GQMZ5FW8"
